name: build 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore ./app1
    - name: Build
      run: dotnet build --no-restore ./app1

    - name: Publish
      run: dotnet publish ./app1 -o publish/

    - uses: actions/upload-artifact@v2.2.4
      with:
        path: app1/publish/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2.0.10
    - uses: azure/webapps-deploy@v2
      name: Deploying to Azure
      with:
        app-name: sample-197978
        publish-profile: ${{ secrets.PUBLISHPROFILE }}
        package: artifact
  
    
