name: build 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: switch to project directory
      run: cd app1/
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --no-restore
  
